algoritmo "semnome"
// Função :
// Autor :
// Data : 16/4/2018
// Seção de Declarações 
var
   a,b,c,d: inteiro
inicio
// Seção de Comandos
   escreva("Informe o valor de A: ")
   leia(a)
   escreva("Informe o valor de B: ")
   leia(b)
   escreva("Informe o valor de C: ")
   leia(c)
   escreva("Informe o valor de D: ")
   leia(d)
   escreval(a + b)
   escreval(a + c)
   escreval(a + d)
   escreval(b + c)
   escreval(b + d)
   escreval(c + d)
fimalgoritmo
