algoritmo "semnome"
// Função :
// Autor :
// Data : 17/4/2018
// Seção de Declarações 
var
   a, b, c, r: inteiro
inicio
// Seção de Comandos
   escreva("Digite um valor para A: ")
   leia(a)
   escreva("Digite um valor para B: ")
   leia(b)
   escreva("Digite um valor para C: ")
   leia(c)
   r <- a * a + b * b + c * c
   escreva("A soma dos quadrados dos números digitados é de: ",r)
fimalgoritmo
