algoritmo "semnome"
// Função :
// Autor :
// Data : 16/4/2018
// Seção de Declarações 
var
   volume, comprimento, largura, altura: real
inicio
// Seção de Comandos
   escreva("Informe o comprimento: ")
   leia(comprimento)
   escreva("Informe a largura: ")
   leia(largura)
   escreva("Informe a altura: ")
   leia(altura)
   volume  <- comprimento * largura * altura
   escreval("O volume da caixa retangular é de: ", volume:2:2," m")
fimalgoritmo
